### ISSUE TITLE
Content created through JS bypasses user defined CSS

### ISSUE THREAD

**Issue by rgouveiamendes** [marimo-team/marimo#2063]
### Describe the bug

I like to tweak all my notebooks' CSS, trying to align their design with the guidelines of my University.
In principle, changing the font for the entire notebook should be easy with something like:
```css
<link href='https://fonts.googleapis.com/css?family=Montserrat:300,300italic,800,800italic' rel='stylesheet'>

<style>
    .marimo, :root {
        --text-font: 'Montserrat';
        --heading-font: 'Montserrat';
    }
</style>
```

It works perfectly everywhere except in the content generated through JavaScript, like `DataFrame`s' , `callout`s', or `accordion`s' outputs.

It also does not work entirely in the `Slides` mode.

### Environment

```json
{
  "marimo": "0.8.0",
  "OS": "Linux",
  "OS Version": "6.9.3-76060903-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.0.3",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pymdown-extensions": "10.9",
    "pygments": "2.18.0",
    "tomlkit": "0.13.2",
    "uvicorn": "0.30.6",
    "starlette": "0.38.2",
    "websockets": "12.0",
    "typing-extensions": "4.12.2",
    "ruff": "0.6.1"
  }
}
```

### Code to reproduce

```python
import marimo as mo

mo.Html("""
<link href='https://fonts.googleapis.com/css?family=Montserrat:300,300italic,800,800italic' rel='stylesheet'>

<style>
    .marimo, :root {
        --text-font: 'Montserrat';
        --heading-font: 'Montserrat';
    }
</style>
""")

mo.callout("This is a callout", kind="neutral")

mo.md(""""This is a sentence where we can see that the change in `:root` took effect in any other place other than JS generated content."")
```

The font doesn't change
