### ISSUE TITLE
Custom CSS file not working

### ISSUE THREAD

**Issue by rgouveiamendes** [marimo-team/marimo#2172]
### Describe the bug

I tried to include custom CSS with a custom CSS file. It did not work in any way. 
I've tired even with the mwe in the docs but that did not work either. 
I've tried to tell Marimo the path through the UI and through `app = mo.App(css_file="custom.css")`
I've tried the full path and the relative path. None of them worked.

### Environment

```json
{
  "marimo": "0.8.7",
  "OS": "Linux",
  "OS Version": "6.9.3-76060903-generic",
  "Processor": "x86_64",
  "Python Version": "3.10.12",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Requirements": {
    "click": "8.1.7",
    "importlib-resources": "missing",
    "jedi": "0.19.1",
    "markdown": "3.7",
    "pymdown-extensions": "10.9",
    "pygments": "2.18.0",
    "tomlkit": "0.13.2",
    "uvicorn": "0.30.6",
    "starlette": "0.38.2",
    "websockets": "13.0.1",
    "typing-extensions": "4.12.2",
    "ruff": "0.6.3"
  }
}
```

### Code to reproduce

My CSS file is as follows (however, I tried the mwe in the docs as well):
```css
@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');

:root {
    --marimo-text-font: 'Montserrat', sans-serif;
    --marimo-heading-font: 'Montserrat', sans-serif;
}
h1 {
    margin-top: 3em !important;
}
h2 {
    margin-top: 2em !important;
}
title {
    font-size: 200%;
    display: block;
    font-weight: bold;
    text-align: left;
    margin: 2em 0 0 0;
}
subtitle {
    font-size: 140%;
    display: block;
    text-align: left;
    margin: 0 0 1.5em 0;
}
author {
    font-size: 120%;
    display: block;
    text-align: left;
    margin: 0 0 1.5em 0;
}
email {
    font-size: 100%;
    display: block;
    text-align: left;
    margin: -1.8em 0 2em 0;
}
li::marker {
    font-weight: bold;
}
.small {
    font-size: 80%;
}
```
