### ISSUE TITLE
Notebook Terminal does not use --marimo-monospace-font (or any other css var from custom.css)

### ISSUE THREAD

**Issue by susl** [marimo-team/marimo#2982]
### Describe the bug

I wanted to open a terminal in Marimo, but my prompt was messed up, because I'm using nerd font and xterm in marimo could not render in properly.

I tried configuring `--marimo-monospace-font` as the documentation says it's the font used for code blocks, so I assume terminal would use it as well. But it does not, an it appears that there's no proper way to configure it.

For now, I did this in `custom.css`, but it's hacky:
```css
@import url("https://mshaugh.github.io/nerdfont-webfonts/build/firacode-nerd-font.css");
.xterm-rows {
    font-family: "FiraCode Nerd Font", monospace !important;
}
```

### Environment

{
  "marimo": "0.9.26",
  "OS": "Darwin",
  "OS Version": "24.1.0",
  "Processor": "i386",
  "Python Version": "3.13.0",
  "Binaries": {
    "Browser": "131.0.6778.86",
    "Node": "v23.3.0"
  },
  "Dependencies": {
    "click": "8.1.7",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.14.2",
    "packaging": "24.2",
    "psutil": "6.1.0",
    "pygments": "2.18.0",
    "pymdown-extensions": "10.12",
    "pyyaml": "6.0.2",
    "ruff": "0.8.0",
    "starlette": "0.41.3",
    "tomlkit": "0.13.2",
    "typing-extensions": "missing",
    "uvicorn": "0.32.1",
    "websockets": "14.1"
  },
  "Optional Dependencies": {}
}

### Code to reproduce

```python
app = marimo.App(width="medium", css_file="custom.css")
```
and 
```css
@import url("https://mshaugh.github.io/nerdfont-webfonts/build/firacode-nerd-font.css");
:root {
    font-family: "FiraCode Nerd Font", monospace !important;
}
```
