### ISSUE TITLE
Support configuration overrides in a pyproject.toml

### ISSUE THREAD

**Issue by mscolnick** [marimo-team/marimo#3069]
### Description

marimo should pick up configuration overrides from the nearest ancestor `pyproject.toml`. The configuration options should be the same and configured like:

```toml
[tool.marimo.ai]
rules = "- prefer polars over pandas\n- make charts using altair"

[tool.marimo.save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = true

[tool.marimo.experimental]
multi_column = true
chat_sidebar = true

[tool.marimo.display]
dataframes = "rich"
```

### Suggested solution

This can (at first) only be configured directly from the `project.toml`. The configuration UI in the marimo editor is reserved for user config, but we can show when the user config is overridden by the project config.
