### ISSUE TITLE
Cell output location to the side

### ISSUE THREAD

**Issue by maurosilber** [marimo-team/marimo#3327]
### Description

In contrast to Jupyter notebooks, Marimo allows to put the output area either `above` and `below`. I still find `above` confusing after years of using Jupyter(-like) notebooks, but it is nice to have more options. I was wondering if you considered moving the output area to the side (right or left). Given that code tends to be 80-100 characters wide, it might make good use of the screen:

![Image](https://github.com/user-attachments/assets/eb0707b2-5abd-4b41-8051-4b56dc54ccb3)

Here I set the width of the cell to 50% and it fits just ~60 characters.

When I'm exploring datasets, I sometimes make subplots with 2 or 3 columns (increasing the complexity of the code) just to make use of the available screen. I have the feeling that moving the output to the side could help with this use case.

Thanks!

### Suggested solution

Add options to move the output to the right (and left).

**Comment by akshayka** [comment]
We have an experimental multi-column view. While not the same as what you've suggested, perhaps it could help?

<img width="929" alt="Image" src="https://github.com/user-attachments/assets/2d463fc7-01df-4f79-80b5-cd205d787ea8" />

**Comment by TeddyHuang-00** [comment]
Sorry for bringing this up again months later. I just stumble across this feature request when searching for something like side-by-side view. I think the multi-column is nice, but it appears to be a different feature that we need. What we need is rather a cell output direction to the side, allowing users to kind of split view, similar to a markdown editor would have. This is what will work for now if you are craving for such a feature. (Maybe using some simple js script to inject tailwind style class into the DOM elements will be nicer)

1. Add the following to your custom CSS

```css
/* Set grid layout for each cell */
.marimo-cell {
  display: grid;
  grid-template-columns: 1fr 1fr;
}

/* Naive fix for rounded corner */
.tray {
  border-radius: 8px;
}
```

2. Set the layout width to be full.
3. Enjoy

![Image](https://github.com/user-attachments/assets/802a26c9-6501-46c8-a325-382b2aaa3eac)

**Comment by mocquin** [comment]
@TeddyHuang-00  I tried but couldn't reproduce your approach : 
- the width display is set to "full"
- a `custom.css` file is located newt to the .py notebook, and contains exactly what you provided about
- cell output are set to "below"

but the outputs are still displayed below the code cell, not to the right

Could you provide the version of marimo used as well ? 

As for the general discussion, I also found that I like the code cell width being `compact`, but would not mind the outputs width to be wider as they otften contain hstack elements for example - their "reading" process is not always meant to be done top-to-bottom, as opposed to a code-cell.

**Comment by TeddyHuang-00** [comment]
@mocquin 

> but the outputs are still displayed below the code cell, not to the right

1. Make sure you only use absolute path or relative path for the css file. NO shell expansion will be performed (so ~ does not work, as well as environment variables)
2. Refresh the page to apply the custom css

> Could you provide the version of marimo used as well ?

It's just CSS. Any version supporting custom css will work. I tried 0.12.6 to 0.13.2 and see no problem.

> As for the general discussion, I also found that I like the code cell width being `compact`, but would not mind the outputs width to be wider... Maybe this approach could also be customized with css ?

Just change the grid spec from `1fr 1fr` to `740px 1fr`. This should match the width of compact layout.

**Comment by cs-hall** [comment]
Found this older thread looking for the same feature!

**Comment by blueforesticarus** [comment]
an updated and slightly improved version (output is sticky)

```css

/* Cell: code + output in row 1, traceback/etc. in row 2. */
.marimo-cell {
    &:not(:has(.output > .markdown)) {
        display: grid;
        grid-template-columns: 0fr minmax(0, 0.4fr) minmax(0, 0.6fr);
        grid-template-rows: auto auto;
        align-items: stretch;
    }

    /* ---- CODE COLUMN ---- */
    >.tray {
        grid-column: 2;
        grid-row: 1;
        align-self: stretch;

        /* Make the wrappers around .cm fill the grid row. */
        >.flex.flex-col.w-full,
        >.flex.flex-col.w-full>.relative {
            height: 100%;
        }

        /* The actual CodeMirror editor sticks independently. */
        .cm {
            position: sticky;
            top: 20px;
        }
    }

    /* ---- OUTPUT COLUMN ---- */
    >.relative:has([data-cell-role="output"]) {
        grid-column: 3;
        grid-row: 1;
        align-self: stretch;
        min-width: 0;

        /* Inner output block sticks independently. */
        >div:has(> [data-cell-role="output"]) {
            position: sticky;
            top: 20px;
        }
    }

    /* ---- TRACEBACK / CONSOLE ---- */
    >.relative.group {
        grid-column: 2 / 4;
        grid-row: 2;
    }
}



/* These interfere with clicking on the right side of output. */
.tray>.shoulder-right,
.tray::after {
    display: none !important;
}

.increase-pointer-area-x {

    &:after,
    &:before {
        z-index: -1;
    }
}


/* Naive fix for rounded corner. */
.tray {
    border-radius: 8px;
}

/* Let the notebook content use the full available viewport width. */
.m-auto {
    max-width: unset !important;
}
```

I'd like to offer the point that side by side:
1. makes much better use of screen real estate in widescreen , especially since code generally targets line under ~80 characters
2. is easier to read because the eye can jump back and forth to the output while reading the input 

sticky makes sense when the output is smaller than the screen, otherwise it is an anti-feature: you can't easily scroll through the output! expand/collapse output button solves this but I see no pure css way to get it to use the full height  of the code block when collapsed, which is un-ideal. 

EDIT: fixed so that sticky divs stay in their grid row
