### ISSUE TITLE
Code snippets - additional suggestions

### ISSUE THREAD

**Issue by peterlee18** [marimo-team/marimo#3901]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

The code snippets are a great idea. I would suggest some snippets around conditional transforms. We have to do these all the time and I find sending example code to the team very helpful.

We find np.select the quickest. See below for an example. data_no_nan is a pandas dataframe.

conditions = [
    (data_no_nan["RDriv"] == "03 Named+1"),
    (data_no_nan["RDriv"] == "04 Named+2"),
    (data_no_nan["RDriv"] == "05 Named+3"),
    (data_no_nan["RDriv"] == "06 Named+4"),
    (data_no_nan["RDriv"] == "07 Named+5"),
    (
        ~data_no_nan["RDriv"].isin(
            ["03 Named+1", "03 Named+2", "03 Named+3", "03 Named+4", "03 Named+5"]
        )
    ),
]
conditions_values = [
    "03 Named",
    "03 Named",
    "03 Named",
    "03 Named",
    "03 Named",
    data_no_nan["RDriv"],
]
data_no_nan["RDriv_grp"] = np.select(conditions, conditions_values)

np.where is also very useful.

I'm sure there are equivalents for polars.

By the way, Marimo is great. Thanks for building it. 

### Your Suggestion for Changes

See baove

**Comment by mscolnick** [comment]
hey @peterlee18, thanks for the suggestion!

if you'd like to contribute a full example, you can add this under `marimo/_snippets/data`. 
if you only find this useful for your team, can you configure additional snippets in your `pyproject.toml`

```toml
[snippets]
custom_paths = ["/path/to/your/snippets/dir"]  # List of paths to directories containing custom snippets
include_default_snippets = true  # Whether to include marimo's default snippets (defaults to true)
```
