### ISSUE TITLE
Error serializing data

### ISSUE THREAD

**Issue by etrotta** [marimo-team/marimo#3972]
### Describe the bug

When I try to run my code after the last update (0.11.13 -> 0.11.14), I get an error saying that a `dict` object has no `.type` attribute. The error mentions serialize line 225, but it's just `LOGGER.error(f"Write error: {e}")`

Looking around a bit it appears to be caused by line 51 in the same file https://github.com/marimo-team/marimo/blob/48e57bdb48cad22fce17fb099ab3e8e66ce375cc/marimo/_server/session/serialize.py#L51

### Environment

<details>

```
{
  "marimo": "0.11.14",
  "OS": "Linux",
  "OS Version": "5.15.167.4-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.10.16",
  "Binaries": {
    "Browser": "--",
    "Node": "--"
  },
  "Dependencies": {
    "click": "8.1.8",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.29.0",
    "packaging": "24.2",
    "psutil": "7.0.0",
    "pygments": "2.19.1",
    "pymdown-extensions": "10.14.3",
    "pyyaml": "6.0.2",
    "ruff": "0.9.9",
    "starlette": "0.46.0",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.34.0",
    "websockets": "15.0"
  },
  "Optional Dependencies": {},
  "Experimental Flags": {}
}
```

</details>

### Code to reproduce

Run all stale after loading https://github.com/etrotta/marimo-learn/blob/main/polars/05_reactive_plots.py in lazy mode

**Comment by etrotta** [comment]
Not sure if relevant, but my config.toml:
<details>

```toml

[display]
theme = "system"
default_width = "medium"
dataframes = "rich"
code_editor_font_size = 14
cell_output = "above"

[snippets]
custom_paths = []
include_default_snippets = true

[completion]
copilot = false
activate_on_typing = true

[experimental]

[ai]
rules = ""

[formatting]
line_length = 120

[package_management]
manager = "uv"

[runtime]
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
auto_instantiate = false
watcher_on_save = "lazy"
output_max_bytes = 8000000
auto_reload = "off"

[save]
autosave_delay = 10000
autosave = "after_delay"
format_on_save = true

[server]
follow_symlink = false
browser = "default"

[keymap]
preset = "default"

[keymap.overrides]

```

</details>
