### ISSUE TITLE
Can't trace config file when overwritten by pyproject.toml

### ISSUE THREAD

**Issue by KennethEnevoldsen** [marimo-team/marimo#4194]
So I am fairly new to Marimo so this might be an error on my end.

I have the following issue: I want autosave turned on but get a warning stating that it is overwritten:

<img width="452" alt="Image" src="https://github.com/user-attachments/assets/77c472b4-4383-4c8b-a45e-569bfe8d3163" />

First, I tried just deleting `pyproject.toml` file in the git repo. This did not change anything. 
Then I tried adding the following to the `pyproject.toml`

```toml
...

[marimo.tool.save]
autosave_delay = 1000
format_on_save = true
autosave = "after_delay"
```

this did not change the problem either.

Then I went out a folder and create a new notebook (assuming that it might look further down my directory):

```
cd ..
mkdir tmp
cd tmp
marimo new
```

Here, I did not have the issue.

This leaves me with a problem and a 'confusion': 

- problem: I can't figure out where the pyproject.toml is located. 
- confusion: Having newer specified marimo in a pyproject.toml before I do not understand why it would overwrite my settings

If I run `marimo config show` then I get:

```toml
...

[save]
autosave_delay = 1000
format_on_save = true
autosave = "after_delay"

...
```

A simple solution might be to allow me to click the pyproject.toml to go to the file or see the path.
