### ISSUE TITLE
Include `uv` in pre-built Docker images

### ISSUE THREAD

**Issue by peter-gy** [marimo-team/marimo#4403]
### Description

I opened PR coollabsio/coolify#5559 to add one-click deployment support for Marimo to servers governed by Coolify. I used the pre-built `ghcr.io/marimo-team/marimo:latest-sql` image to do so.

I had to resort to a super ugly `healthcheck` as there is no HTTP client present in the image.

```yml
healthcheck:
      test:
        - CMD
        - bash
        - -c
        - "pip install --upgrade pip -q; pip install requests -q; python -c 'import requests as r;r.get(\"http://0.0.0.0:8080\").raise_for_status()'" 
```

Adding `uv` to the images would allow for a nice Pythonic solution.

### Suggested solution

Make `uv` and `uvx` available in the images by adding the single line: `COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/` to the `base` image.

This would allow simplifying the healthcheck to something like `uvx --with 'httpx[cli]' httpx {marimo-instance-url}`.

### Alternative

- Live with the current solution
- Build a custom image based on `ghcr.io/marimo-team/marimo:latest-sql` to add some HTTP client at build time

### Additional context

If you agree with the one-liner solution I proposed, I would be glad to open a PR.
