### ISSUE TITLE
Bug Codestral AI integration

### ISSUE THREAD

**Issue by laguill** [marimo-team/marimo#4819]
### Description

Integrate codestral from Mistral in marimo.

### Suggested solution

I tried to edit marimo.toml
With this parameters but without success

```toml
[ai.open_ai]
base_url = "https://codestral.mistral.ai/v1/chat/completion"
model = "codestral/codestral-latest"
api_key = "***"
```

### Will you submit a PR?

- [ ] Yes
