### ISSUE TITLE
Support removing the "Made with Marimo" and "Static Notebook Popup" when exporting to static HTML

### ISSUE THREAD

**Issue by aschreiber1** [marimo-team/marimo#5355]
### Description

I get why these features are here, but in an enterprise setting it's unprofessional to have the "Made with Marimo" logo. Also in many cases when people are looking at static HTML files they know they are looking at static HTML files and it's nice to be able to disable that warning. That warning takes up 1/3 of a phone screen and it is the first thing you see when loading a static HTML on a phone, and it looks terrible, immediately cause poor user experience. 

It seems these are added by javascript and not static HTML so seems these are hard to get rid of by users without it being built into the marimo export feature. 

### Suggested solution

Add parameters to marino-export that disable those getting added to the page

### Will you submit a PR?

- [ ] Yes

**Comment by akshayka** [comment]
Thanks for the feature request. In the meantime it should be possible to hide these with custom CSS.

> That warning takes up 1/3 of a phone screen and it is the first thing you see when loading a static HTML on a phone, and it looks terrible, immediately cause poor user experience.

We can improve this for sure (I thought we already had but perhaps not). What version of marimo are you using?

**Comment by aschreiber1** [comment]
We are on 13.15 so a very recent version. Any hints on the custom css? I tried to remove the html tags for them but it seems the JavaScript perhaps adds them back?

**Comment by seanmcleod70** [comment]
Having recently upgraded from 13.15 to 14.x I noticed that the warning is a fair bit smaller now.

**Comment by FrenkT** [comment]
@aschreiber1 not sure if still useful, but I had some success with the following custom CSS:

```css
[data-testid="watermark"] {
  display: none !important;
}

[data-testid="static-notebook-banner"] {
  display: none !important;
}

[role="region"][aria-label*="Notifications"] {
  display: none !important;
}
```

**Comment by mscolnick** [comment]
Thanks @FrenkT for the selectors, those are right. The robust way to apply them is marimo’s supported `display.custom_css`:

```toml
[tool.marimo.display]
custom_css = ["hide-branding.css"]
```

```css
[data-testid="watermark"] { display: none !important; }
[data-testid="static-notebook-banner"] { display: none !important; }
[role="region"][aria-label*="Notifications"] { display: none !important; }
```

Keeping this open as a feature request for a first-class export flag.
