### ISSUE TITLE
Marimo behind Jupyter / JupyterHub 

### ISSUE THREAD

**Issue by scls19fr** [marimo-team/marimo#905]
### Description

Hello,

Quite similar to #904 

This may be really interesting to have Marimo available behind [Jupyter](https://jupyter.org/) / [JupyterHub](https://jupyterhub.readthedocs.io/) as Pluto.jl is doing in https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-julia-notebook with jupyter-pluto-proxy

![image](https://github.com/marimo-team/marimo/assets/109167/669aa6ba-e1d4-49f0-acb2-59ac75a6d73a)

Kind regards

### Suggested solution

Implements something similar to [jupyter-pluto-proxy](https://github.com/IllumiDesk/jupyter-pluto-proxy)

**Comment by mscolnick** [comment]
In the short term, this will slow down our developer velocity since its another environment combination that will need to be test, supported, maintained. 

Unless there is a neat solution to support this without sacrificing developer velocity, I not sure this would be supported (at least in core).

Taking a step back: why do you want to do this?

**Comment by scls19fr** [comment]
I understand perfectly that's an important task to achieve that and your team bandwidth is limited.
Such a solution will make it possible to edit python files on a VPS without the need to have Python running on your computer. Moreover it could possibly open the multi user features that some other users are requesting (this part will be even harder as you will have to provide isolated environment for each user)

**Comment by scls19fr** [comment]
My pleasure!

If you want to try this kind of solution quickly with Pluto... here is a `docker-compose.yml` file for that purpose

```
version: '3.3'
services:
  jupyter_scipy_notebook:
    image: quay.io/jupyter/scipy-notebook:2024-02-24
    ports:
      - 10000:8888
    volumes:
      - ./local_dir:/home/jovyan/work
      - ~/data:/home/jovyan/data
      - ./certs/private.key:/etc/ssl/notebook/notebook.key
      - ./certs/certificate.crt:/etc/ssl/notebook/notebook.crt
    command: "start-notebook.py \
      --ServerApp.keyfile=/etc/ssl/notebook/notebook.key \
      --ServerApp.certfile=/etc/ssl/notebook/notebook.crt"
    #restart: unless-stopped
    restart: always
``` 

and run it using `docker compose up` (you probably won't need keyfile and certfile as it's not for production (no SSL)
